### ISSUE TITLE
Inline CSS does not get fixed

### ISSUE THREAD

**Issue by extremeshok** [webaware/ssl-insecure-content-fixer#1]
Example: 
background-image: url(http://example.com/themes/wp-content/theme/images/image.jpg)

Will not become https://

**Comment by webaware** [comment]
Thanks, now fixed in git, will release soon to WordPress.org but you can download from here for now:

https://www.dropbox.com/s/9hbdstod8wyebhl/ssl-insecure-content-fixer-2.1.4-dev.zip?dl=0
