### ISSUE TITLE
Add exclusions

### ISSUE THREAD

**Issue by markdwhite** [webaware/ssl-insecure-content-fixer#4]
I have an issue where dynamically included content contains HTTP URLs that do not have an HTTPS equivalent. For now the only option to exclude these seems to be such as:

```
	public static function fixContent_src_callback($matches) {
		// Don't convert Amazon images as they fail on https
		if (strpos($matches[0], 'http://ecx.images-amazon.com') === 0) {
			return $matches[0];
		}
		return 'https' . substr($matches[0], 4);
	}
```

Is there a better solution as hardcoded changes are not really a long-term solution? 

Thanks.

**Comment by webaware** [comment]
Great idea. I've added a filter that you can call. It passes an array, to which you can add your domain(s). It works on content replacements, but not on enqueued scripts/stylesheets (keeping that as lightweight as possible). NB: just the domain, not a URI (i.e. no `http://`)

e.g.

```php
add_filter('ssl_insecure_content_domain_exclusions', function($domains) {
    $domains[] = 'example.com';
    return $domains;
});
```

Here's a dev copy of the next release. I'll get it out sometime next week -- I have a few things to release next week, so it might be mid to late in the week, but next week anyway.

https://www.dropbox.com/s/hd5qjyizy16alxn/ssl-insecure-content-fixer-2.2.4-dev.zip?dl=1

cheers!

**Comment by markdwhite** [comment]
A filter is perfect! I'm having a few days away from work, but will test the zip soon.

Many thanks for the prompt reply :)

**Comment by markdwhite** [comment]
Just got back from vacation and saw that version 2.4 has now been released - worked perfectly thanks :-)
